version: "3.8"

services:
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - JWT_SECRET=${JWT_SECRET}
  #   volumes:
  #     - ${APPDATA}workout:/config
  #   ports:
  #     - ${BACKEND_PORT}:3000
  #   networks:
  #     - default
  #     - workout
  #   restart: always

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./backend/db/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    volumes:
      - ./backend/db/adminer:/adminer
    ports:
      - 1313:8080
    restart: always

networks:
  workout:
    external: true
