version: '3.8'

services:
  workout:
    container_name: workout
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA}workout:/config
    ports:
      - 3306:3306
    networks:
      - default
      - workout
    restart: always

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    user: '${PUID}:${PGID}'
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    volumes:
      - ${APPDATA}adminer:/adminer
    ports:
      - 8080:8080
    restart: always

networks:
  workout:
    external: true
